# Generated by Django 3.1.5 on 2021-01-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='clasification',
            new_name='classification',
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_link',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace Vendedor'),
        ),
    ]
